// ===== LIBRARY DATA — Thư Viện THPT Dương Đông =====
const LIBRARY_DATA = {

  // Bộ Sưu Tập (Collections)
  collections: [
    { code:'TK', name:'Sách Tham Khảo', count:1574, loan:30, icon:'📘', color:'#3b82f6', desc:'Sách tham khảo các môn học, bài tập, nâng cao' },
    { code:'GK', name:'Sách Giáo Khoa', count:518, loan:30, icon:'📗', color:'#10b981', desc:'Sách giáo khoa chính quy từ lớp 10 đến lớp 12' },
    { code:'LIBROS', name:'Sách Mượn (LIBROS)', count:164, loan:14, icon:'📙', color:'#f59e0b', desc:'Sách cho mượn ngắn hạn, phục vụ nghiên cứu' },
    { code:'NV', name:'Sách Nghiệp Vụ', count:106, loan:255, icon:'📕', color:'#8b5cf6', desc:'Tài liệu nghiệp vụ dành cho giáo viên' },
    { code:'BT', name:'Báo & Tạp Chí', count:29, loan:30, icon:'📰', color:'#f43f5e', desc:'Báo thiếu nhi, tạp chí giáo dục' },
    { code:'TIENGANH', name:'Sách Tiếng Anh', count:9, loan:14, icon:'🇬🇧', color:'#06b6d4', desc:'Tài liệu học tiếng Anh, sách song ngữ' },
  ],

  // DDC (Dewey Decimal Classification)
  ddc: [
    { num:'000', name:'Tổng quát', nameVi:'Tin học, thông tin & tổng quát', count:85, color:'#64748b', subs:['Tin học','Thông tin','Bách khoa','Thư viện'] },
    { num:'100', name:'Triết học & Tâm lý', nameVi:'Triết học, tâm lý học, đạo đức', count:92, color:'#8b5cf6', subs:['Triết học','Tâm lý','Đạo đức','Logic'] },
    { num:'200', name:'Tôn giáo', nameVi:'Tôn giáo, tín ngưỡng', count:18, color:'#a78bfa', subs:['Phật giáo','Tín ngưỡng'] },
    { num:'300', name:'Khoa học Xã hội', nameVi:'KHXH, luật, giáo dục, kinh tế', count:380, color:'#f59e0b', subs:['Xã hội học','Chính trị','Kinh tế','Luật','Giáo dục','Phong tục'] },
    { num:'400', name:'Ngôn ngữ', nameVi:'Ngôn ngữ học, từ điển', count:65, color:'#06b6d4', subs:['Tiếng Việt','Tiếng Anh','Từ điển','Ngữ pháp'] },
    { num:'500', name:'Khoa học Tự nhiên', nameVi:'Toán, Lý, Hóa, Sinh, Địa lý tự nhiên', count:420, color:'#10b981', subs:['Toán','Vật lý','Hóa học','Sinh học','Thiên văn','Địa chất'] },
    { num:'600', name:'Công nghệ', nameVi:'Y học, kỹ thuật, nông nghiệp', count:78, color:'#f97316', subs:['Y học','Kỹ thuật','Nông nghiệp','Công nghệ'] },
    { num:'700', name:'Nghệ thuật', nameVi:'Nghệ thuật, âm nhạc, thể thao, giải trí', count:95, color:'#ec4899', subs:['Mỹ thuật','Âm nhạc','Thể thao','Giải trí','Nhiếp ảnh'] },
    { num:'800', name:'Văn học', nameVi:'Văn học Việt Nam & thế giới', count:650, color:'#3b82f6', subs:['Văn học VN','Văn học nước ngoài','Thơ','Truyện ngắn','Tiểu thuyết','Truyện tranh'] },
    { num:'900', name:'Lịch sử & Địa lý', nameVi:'Lịch sử, địa lý, tiểu sử', count:417, color:'#f43f5e', subs:['Lịch sử VN','Lịch sử thế giới','Địa lý','Tiểu sử','Du lịch'] },
  ],

  // Chủ đề (Subjects)
  subjects: [
    { name:'Ngữ văn', icon:'✍️', count:320, grades:'10-12', category:'Môn học' },
    { name:'Toán', icon:'📐', count:280, grades:'10-12', category:'Môn học' },
    { name:'Vật lý', icon:'⚛️', count:165, grades:'10-12', category:'Môn học' },
    { name:'Hóa học', icon:'🧪', count:150, grades:'10-12', category:'Môn học' },
    { name:'Sinh học', icon:'🧬', count:135, grades:'10-12', category:'Môn học' },
    { name:'Lịch sử', icon:'🏛️', count:190, grades:'10-12', category:'Môn học' },
    { name:'Địa lý', icon:'🌏', count:145, grades:'10-12', category:'Môn học' },
    { name:'Tiếng Anh', icon:'🇬🇧', count:120, grades:'10-12', category:'Môn học' },
    { name:'Tin học', icon:'💻', count:75, grades:'10-12', category:'Môn học' },
    { name:'Giáo dục Công dân', icon:'⚖️', count:85, grades:'10-12', category:'Môn học' },
    { name:'Công nghệ', icon:'🔧', count:45, grades:'10-12', category:'Môn học' },
    { name:'Giáo dục Quốc phòng', icon:'🎖️', count:30, grades:'10-12', category:'Môn học' },
    { name:'Văn học Việt Nam', icon:'📜', count:210, grades:'', category:'Chuyên đề' },
    { name:'Văn học Nước ngoài', icon:'🌍', count:95, grades:'', category:'Chuyên đề' },
    { name:'Truyện tranh / Manga', icon:'🎨', count:48, grades:'', category:'Chuyên đề' },
    { name:'Tủ sách Biển Đảo', icon:'🏝️', count:35, grades:'', category:'Chuyên đề' },
    { name:'Kỹ năng sống', icon:'🌱', count:65, grades:'', category:'Chuyên đề' },
    { name:'Khoa học thường thức', icon:'🔬', count:42, grades:'', category:'Chuyên đề' },
    { name:'Sáng kiến kinh nghiệm', icon:'💡', count:55, grades:'', category:'Nghiệp vụ' },
    { name:'Atlat Địa lý Việt Nam', icon:'🗺️', count:28, grades:'', category:'Công cụ' },
    { name:'Phú Quốc & Kiên Giang', icon:'🌴', count:22, grades:'', category:'Địa phương' },
    { name:'Bác Hồ & Đảng', icon:'⭐', count:40, grades:'', category:'Chính trị' },
    { name:'Tâm lý học đường', icon:'🧠', count:38, grades:'', category:'Chuyên đề' },
    { name:'Du lịch', icon:'✈️', count:30, grades:'', category:'Chuyên đề' },
    { name:'Lập bản đồ tư duy', icon:'🗂️', count:15, grades:'', category:'Phương pháp' },
  ],

  // Từ khoá (Keywords / Tags)
  keywords: [
    { word:'Toán học', weight:5 },{ word:'Ngữ văn', weight:5 },{ word:'Vật lý', weight:4 },
    { word:'Hóa học', weight:4 },{ word:'Sinh học', weight:4 },{ word:'Lịch sử Việt Nam', weight:5 },
    { word:'Địa lý', weight:4 },{ word:'Tiếng Anh', weight:3 },{ word:'Tin học', weight:3 },
    { word:'Truyện tranh', weight:3 },{ word:'Kỹ năng sống', weight:3 },{ word:'Sách giáo khoa', weight:5 },
    { word:'Phú Quốc', weight:4 },{ word:'Biển đảo', weight:3 },{ word:'Văn học', weight:5 },
    { word:'Tiểu thuyết', weight:3 },{ word:'Truyện ngắn', weight:3 },{ word:'Thơ', weight:2 },
    { word:'Bài tập', weight:4 },{ word:'Đề thi', weight:4 },{ word:'Ôn tập', weight:3 },
    { word:'Lớp 10', weight:3 },{ word:'Lớp 11', weight:3 },{ word:'Lớp 12', weight:4 },
    { word:'Nâng cao', weight:3 },{ word:'Tham khảo', weight:4 },{ word:'Giáo dục', weight:3 },
    { word:'Bác Hồ', weight:3 },{ word:'Đạo đức', weight:2 },{ word:'Tâm lý', weight:2 },
    { word:'Du lịch', weight:2 },{ word:'Văn hóa', weight:3 },{ word:'Khoa học', weight:3 },
    { word:'Công nghệ', weight:2 },{ word:'Nghệ thuật', weight:2 },{ word:'Âm nhạc', weight:1 },
    { word:'Thể dục', weight:2 },{ word:'Quốc phòng', weight:2 },{ word:'Kinh tế', weight:2 },
    { word:'Manga Teen', weight:2 },{ word:'Bách khoa', weight:2 },{ word:'Từ điển', weight:2 },
    { word:'Atlat', weight:2 },{ word:'Sáng kiến', weight:2 },{ word:'Nghiệp vụ', weight:2 },
    { word:'Bản đồ tư duy', weight:2 },{ word:'Tony Buzan', weight:1 },{ word:'Đảng', weight:2 },
  ],

  // Sample books for search/display
  books: [
    { title:'Bồi dưỡng học sinh giỏi sinh học THPT', author:'Nhiều tác giả', ddc:'576', coll:'TK', subject:'Sinh học' },
    { title:'Hướng dẫn áp dụng chuẩn nghề nghiệp giáo viên', author:'Bộ GD&ĐT', ddc:'344.597', coll:'TK', subject:'Giáo dục' },
    { title:'Lý Quang Diệu — Người cha lập quốc', author:'Nhiều tác giả', ddc:'895.6', coll:'TK', subject:'Tiểu sử' },
    { title:'Blog thành công của teen', author:'Nhiều tác giả', ddc:'158.083', coll:'TK', subject:'Kỹ năng sống' },
    { title:'Bạn trai tháo vát', author:'Nhiều tác giả', ddc:'646.700', coll:'TK', subject:'Kỹ năng sống' },
    { title:'Kể chuyện Bác Hồ (Tập 1)', author:'Nhiều tác giả', ddc:'959.704', coll:'TK', subject:'Lịch sử' },
    { title:'Kể chuyện Bác Hồ (Tập 2)', author:'Nhiều tác giả', ddc:'959.704', coll:'TK', subject:'Lịch sử' },
    { title:'Kể chuyện Bác Hồ (Tập 3)', author:'Nhiều tác giả', ddc:'959.704', coll:'TK', subject:'Lịch sử' },
    { title:'Phú Quốc, hòn ngọc của biển Đông', author:'Nguyễn Hữu Luyện', ddc:'915.9', coll:'TK', subject:'Du lịch' },
    { title:'Phú Quốc — Đảo Ngọc', author:'Nguyễn Ngọc Bích', ddc:'915.9', coll:'TK', subject:'Du lịch' },
    { title:'Phú Quốc — Hòn đảo ngọc', author:'Nguyễn Hữu Hiệp', ddc:'915.9', coll:'TK', subject:'Du lịch' },
    { title:'Phú Quốc: Viên ngọc quý của Việt Nam', author:'Nguyễn Văn Hiếu', ddc:'915.9', coll:'TK', subject:'Du lịch' },
    { title:'Lập bản đồ tư duy', author:'Tony Buzan', ddc:'153.4', coll:'TK', subject:'Tâm lý' },
    { title:'Sách giáo khoa mẫu lớp 12', author:'Bộ GD&ĐT', ddc:'373', coll:'GK', subject:'Giáo dục' },
    { title:'Toán 10 — Tập 1', author:'Bộ GD&ĐT', ddc:'510', coll:'GK', subject:'Toán' },
    { title:'Toán 10 — Tập 2', author:'Bộ GD&ĐT', ddc:'510', coll:'GK', subject:'Toán' },
    { title:'Toán 11', author:'Bộ GD&ĐT', ddc:'510', coll:'GK', subject:'Toán' },
    { title:'Toán 12', author:'Bộ GD&ĐT', ddc:'510', coll:'GK', subject:'Toán' },
    { title:'Ngữ văn 10 — Tập 1', author:'Bộ GD&ĐT', ddc:'895.922', coll:'GK', subject:'Ngữ văn' },
    { title:'Ngữ văn 11 — Tập 1', author:'Bộ GD&ĐT', ddc:'895.922', coll:'GK', subject:'Ngữ văn' },
    { title:'Ngữ văn 12 — Tập 1', author:'Bộ GD&ĐT', ddc:'895.922', coll:'GK', subject:'Ngữ văn' },
    { title:'Vật lý 10', author:'Bộ GD&ĐT', ddc:'530', coll:'GK', subject:'Vật lý' },
    { title:'Vật lý 11', author:'Bộ GD&ĐT', ddc:'530', coll:'GK', subject:'Vật lý' },
    { title:'Vật lý 12', author:'Bộ GD&ĐT', ddc:'530', coll:'GK', subject:'Vật lý' },
    { title:'Hóa học 10', author:'Bộ GD&ĐT', ddc:'540', coll:'GK', subject:'Hóa học' },
    { title:'Hóa học 11', author:'Bộ GD&ĐT', ddc:'540', coll:'GK', subject:'Hóa học' },
    { title:'Hóa học 12', author:'Bộ GD&ĐT', ddc:'540', coll:'GK', subject:'Hóa học' },
    { title:'Sinh học 10', author:'Bộ GD&ĐT', ddc:'570', coll:'GK', subject:'Sinh học' },
    { title:'Sinh học 11', author:'Bộ GD&ĐT', ddc:'570', coll:'GK', subject:'Sinh học' },
    { title:'Sinh học 12', author:'Bộ GD&ĐT', ddc:'570', coll:'GK', subject:'Sinh học' },
    { title:'Lịch sử 10', author:'Bộ GD&ĐT', ddc:'959', coll:'GK', subject:'Lịch sử' },
    { title:'Lịch sử 11', author:'Bộ GD&ĐT', ddc:'959', coll:'GK', subject:'Lịch sử' },
    { title:'Lịch sử 12', author:'Bộ GD&ĐT', ddc:'959', coll:'GK', subject:'Lịch sử' },
    { title:'Địa lý 10', author:'Bộ GD&ĐT', ddc:'910', coll:'GK', subject:'Địa lý' },
    { title:'Địa lý 11', author:'Bộ GD&ĐT', ddc:'910', coll:'GK', subject:'Địa lý' },
    { title:'Địa lý 12', author:'Bộ GD&ĐT', ddc:'910', coll:'GK', subject:'Địa lý' },
    { title:'Tiếng Anh 10', author:'Bộ GD&ĐT', ddc:'420', coll:'GK', subject:'Tiếng Anh' },
    { title:'Tiếng Anh 11', author:'Bộ GD&ĐT', ddc:'420', coll:'GK', subject:'Tiếng Anh' },
    { title:'Tiếng Anh 12', author:'Bộ GD&ĐT', ddc:'420', coll:'GK', subject:'Tiếng Anh' },
    { title:'GDCD 10', author:'Bộ GD&ĐT', ddc:'370', coll:'GK', subject:'Giáo dục Công dân' },
    { title:'Tin học 10', author:'Bộ GD&ĐT', ddc:'004', coll:'GK', subject:'Tin học' },
    { title:'Tủ sách Phụ nữ Việt Nam', author:'Nhiều tác giả', ddc:'305.4', coll:'TK', subject:'Xã hội' },
    { title:'Atlat Địa lý Việt Nam', author:'Bộ GD&ĐT', ddc:'912', coll:'TK', subject:'Địa lý' },
    { title:'Truyện Doraemon tập 1', author:'Fujiko F. Fujio', ddc:'741.5', coll:'BT', subject:'Truyện tranh' },
    { title:'Truyện Conan tập 1', author:'Aoyama Gosho', ddc:'741.5', coll:'BT', subject:'Truyện tranh' },
    { title:'English Grammar in Use', author:'Raymond Murphy', ddc:'425', coll:'TIENGANH', subject:'Tiếng Anh' },
  ],
};
